### ISSUE TITLE
testcases generate images all black

### ISSUE THREAD

**Issue by caffeAndtf** [dukebw/LOHO#1]
result:
![result](https://user-images.githubusercontent.com/34699605/115334087-50267f80-a1cd-11eb-9c34-1b3456d719ca.png)

synth image:
![synth-1499](https://user-images.githubusercontent.com/34699605/115334162-72b89880-a1cd-11eb-8b10-cdc4bae003ef.png)

**Comment by RohitSaha** [comment]
Please ensure that you are running the script with the right arguments, as mentioned in the README. Trying combinations other than the ones specified in the README can lead to unrealistic output.
