### ISSUE TITLE
Importing compare_ssim error

### ISSUE THREAD

**Issue by dwyoun** [dukebw/LOHO#11]
Hi, 

Really thank you for sharing you works.

By the way, I suppose that networks/lpips/__init__.py should be fixed.  May need to fix line 6.

from skimage.metrics import structural_similarity as compare_ssim
instead of
from skimage.measure import compare_ssim

Thanks again.

Cheers,
Dale

**Comment by RohitSaha** [comment]
Thanks Dale for pointing this out!
