### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/inference.pth',I ran into this mistake,Excuse me,Do you know how to solve it?

### ISSUE THREAD

**Issue by 123456klk1** [dukebw/LOHO#13]

**Comment by 123456klk1** [comment]
In order to run LOHO, you have to download the necessary model checkpoints. We provide instructions to download checkpoints:
* Download the checkpoints for Graphonomy and StyleGANv2 from: https://drive.google.com/drive/folders/10goJlS18m9si3fBOmQKjszS2m9tfjfp7?usp=sharing
* Place the files in the folder: checkpoints/

**Comment by Anas-jaffery-kodexolab** [comment]
@123456klk1 I have the downloaded model checkpoints and place them in respective folder but still I am facing this issue
