### ISSUE TITLE
why it takes so long?

### ISSUE THREAD

**Issue by lijiae** [dukebw/LOHO#4]
Thanks for your excellent work!
I downloaded your code and make it run like what your README says, but I found it takes about 16mins to get a result. Is this normal or did I miss some important steps?
My gpu is one GTX 2080Ti.

**Comment by RohitSaha** [comment]
Thank you for your interest in LOHO.

Yes, 16 mins sounds about right. Since LOHO is an optimization-based framework, it has to be run for a total of 2000 iterations, which take about 16mins depending on the resolution of the image. Lower resolution images should take shorter time.
