### ISSUE TITLE
How to make a custom mask?

### ISSUE THREAD

**Issue by Eunchan24** [dukebw/LOHO#5]
Thank you for your hard work!

I'd like to know how to train the logo.

I want to run it with the data I have instead of the sample data provided, what should I do?
How can I make a mask of the data I have?

**Comment by RohitSaha** [comment]
To get the mask for the data that you have, you can run the Graphonomy network. 

Graphonomy creates segmentation mask of the image you provide, using which you can select the facial and hair regions. Next, you can binarize them to get the corresponding masks.

**Comment by windshg** [comment]
> 
how to generate mask with graphonomy_process.py specifically？
