### ISSUE TITLE
How to cal ssim and psnr

### ISSUE THREAD

**Issue by XYFFFFFF** [dukebw/LOHO#8]
i notice that you don't have the label of the train img, so how to calculate the ssim and psnr. Thanks a lot~

**Comment by RohitSaha** [comment]
Hi, to compute the SSIM and PSNR, the facial regions of the synthesized image and source identity image (I_1) are compared. We have access to the facial mask (M_1) of I_1. Therefore, the PSNR can be computed between (I_1 * M_1) and (I_G * M_1). Hope this information helps.
